import { GeneratedWorld } from '../../engine/worldgen/index.js';
import { onRollback } from '../../storage/unit-of-work.js';

export class WorldManager {
    private worlds: Map<string, GeneratedWorld> = new Map();

    create(id: string, world: GeneratedWorld): void {
        if (this.worlds.has(id)) {
            throw new Error(`World ${id} already exists`);
        }
        // A world generated by a call that later rolls back must not outlive it.
        onRollback(() => { this.worlds.delete(id); }, `world:${id}`);
        this.worlds.set(id, world);
    }

    get(id: string): GeneratedWorld | null {
        return this.worlds.get(id) || null;
    }

    delete(id: string): boolean {
        return this.worlds.delete(id);
    }

    list(): string[] {
        return Array.from(this.worlds.keys());
    }
}

// Singleton for server lifetime
let instance: WorldManager | null = null;
export function getWorldManager(): WorldManager {
    if (!instance) instance = new WorldManager();
    return instance;
}
